In [3]:
# 导包
import numpy as np
import time
import random

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
lists = []
for i in range(100):
    lists.append(random.randint(1,50))
lists

[26,
 48,
 41,
 35,
 22,
 17,
 34,
 23,
 31,
 1,
 43,
 12,
 30,
 30,
 48,
 13,
 46,
 6,
 18,
 29,
 14,
 9,
 4,
 14,
 45,
 29,
 10,
 40,
 49,
 17,
 8,
 47,
 26,
 11,
 15,
 7,
 43,
 13,
 28,
 33,
 48,
 1,
 41,
 22,
 50,
 7,
 19,
 43,
 6,
 30,
 19,
 36,
 35,
 32,
 27,
 6,
 49,
 11,
 5,
 10,
 28,
 2,
 5,
 11,
 8,
 12,
 6,
 24,
 25,
 2,
 19,
 31,
 7,
 46,
 34,
 14,
 5,
 19,
 47,
 13,
 49,
 32,
 20,
 48,
 36,
 14,
 31,
 6,
 20,
 49,
 15,
 15,
 46,
 26,
 29,
 13,
 38,
 44,
 6,
 1]

In [8]:
lists.append(2000)
lists

[26,
 48,
 41,
 35,
 22,
 17,
 34,
 23,
 31,
 1,
 43,
 12,
 30,
 30,
 48,
 13,
 46,
 6,
 18,
 29,
 14,
 9,
 4,
 14,
 45,
 29,
 10,
 40,
 49,
 17,
 8,
 47,
 26,
 11,
 15,
 7,
 43,
 13,
 28,
 33,
 48,
 1,
 41,
 22,
 50,
 7,
 19,
 43,
 6,
 30,
 19,
 36,
 35,
 32,
 27,
 6,
 49,
 11,
 5,
 10,
 28,
 2,
 5,
 11,
 8,
 12,
 6,
 24,
 25,
 2,
 19,
 31,
 7,
 46,
 34,
 14,
 5,
 19,
 47,
 13,
 49,
 32,
 20,
 48,
 36,
 14,
 31,
 6,
 20,
 49,
 15,
 15,
 46,
 26,
 29,
 13,
 38,
 44,
 6,
 1,
 2000]

#### 使用三西格玛原则检测异常值

In [9]:
# 计算平均值
data_mean = np.mean(lists)
data_mean

43.64356435643565

In [10]:
# 标准差
data_std = np.std(lists)
data_std

196.20269293770724

In [11]:
np.abs(lists-data_mean)>3*data_std

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True])

In [12]:
bol = np.abs(lists-data_mean)>3*data_std
# 将list转为数组
lists = np.array(lists)
lists[bol]

array([2000])

#### 异常值检测的方法：三西格玛原则，格拉布斯原则，迪克逊准则，肖维勒准则，t检验，f检验

#### 矩阵

In [13]:
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [14]:
a*2

array([[0, 2],
       [4, 6]])

In [15]:
b = np.arange(4,8).reshape((2,2))
b

array([[4, 5],
       [6, 7]])

In [16]:
a+b

array([[ 4,  6],
       [ 8, 10]])

In [17]:
# 矩阵的乘法，要求前者的列数等于后者的行数
# 矩阵的乘法
np.dot(a,b)

array([[ 6,  7],
       [26, 31]])

In [18]:
a*b  # ?????

array([[ 0,  5],
       [12, 21]])

In [19]:
# 矩阵的除法
a1 = np.arange(16).reshape(4,4)
b1 = np.arange(2,18).reshape(4,4)
np.divide(a1,b1)

array([[0.        , 0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      , 0.77777778],
       [0.8       , 0.81818182, 0.83333333, 0.84615385],
       [0.85714286, 0.86666667, 0.875     , 0.88235294]])